runtime: python
threadsafe: yes
env: flex
entrypoint: gunicorn -b :$PORT app:app

runtime_config:
  python_version: 3

env_variables:
    # Replace user, password, database, and instance connection name with the values obtained
    # when configuring your Cloud SQL instance.
    SQLALCHEMY_DATABASE_URI: >-
      postgresql+psycopg2://postgres:dbiscool@/booksdb?host=/cloudsql/project3-183521:us-central1:booksdb

beta_settings:
    cloud_sql_instances: project3-183521:us-central1:booksdb

handlers:
- url: /.*
  script: app.app